/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.striker_quest;

/**
 *
 * @author Usuario
 */
public class TelaGol extends javax.swing.JFrame {

    /**
     * Creates new form TelaGol
     */
    public TelaGol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcao1Button = new javax.swing.JButton();
        opcao2Button = new javax.swing.JButton();
        opcao3Button = new javax.swing.JButton();
        opcao4Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opcao1Button.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 56)); // NOI18N
        opcao1Button.setText("1");
        opcao1Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        opcao1Button.setContentAreaFilled(false);
        opcao1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcao1ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(opcao1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 600, 210));

        opcao2Button.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 56)); // NOI18N
        opcao2Button.setText("2");
        opcao2Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        opcao2Button.setContentAreaFilled(false);
        getContentPane().add(opcao2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 230, 680, 200));

        opcao3Button.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 56)); // NOI18N
        opcao3Button.setText("3");
        opcao3Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        opcao3Button.setContentAreaFilled(false);
        getContentPane().add(opcao3Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, 680, 200));

        opcao4Button.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 56)); // NOI18N
        opcao4Button.setText("4");
        opcao4Button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        opcao4Button.setContentAreaFilled(false);
        opcao4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcao4ButtonActionPerformed(evt);
            }
        });
        getContentPane().add(opcao4Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 600, 190));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/cris e gol img.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1760, 1040));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcao1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcao1ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcao1ButtonActionPerformed

    private void opcao4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcao4ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcao4ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton opcao1Button;
    private javax.swing.JButton opcao2Button;
    private javax.swing.JButton opcao3Button;
    private javax.swing.JButton opcao4Button;
    // End of variables declaration//GEN-END:variables
}
